%% Figure Settings
close all

set(groot, 'defaultAxesTickDir', 'in');
set(groot,  'defaultAxesTickDirMode', 'manual');
set(0, 'DefaultFigureColor', 'w', ...
'DefaultAxesFontSize', 10, ...
'DefaultAxesFontName', 'Calibri', ...
'DefaultAxesLayer', 'Top', ...
'DefaultAxesTickLength', [.005 .005], ...
'DefaultAxesBox','Off',...
'DefaultLineLineWidth', 1, ...
'DefaultTextFontSize', 10, ...
'DefaultTextFontName', 'Calibri');

%% other settings

'DefaultFigurePaperType', 'a4letter', ...
'DefaultAxesColor', 'white', ...
'DefaultAxesDrawmode', 'fast', ...
'DefaultAxesFontUnits', 'points', ...
'DefaultAxesFontAngle', 'normal', ...
'DefaultAxesGridLineStyle', ':', ...
'DefaultAxesInterruptible', 'on', ...
'DefaultAxesNextPlot', 'replace', ...
'DefaultAxesUnits', 'normalized', ...
'DefaultAxesXcolor', [0, 0, 0], ...
'DefaultAxesYcolor', [0, 0, 0], ...
'DefaultAxesZcolor', [0, 0, 0], ...
'DefaultAxesVisible', 'on', ...
'DefaultLineColor', 'Red', ...
'DefaultLineLineStyle', '-', ...
'DefaultLineMarker', 'none', ...
'DefaultLineMarkerSize', 8, ...
'DefaultTextColor', [0, 0, 0], ...
'DefaultTextFontUnits', 'Points', ...
'DefaultTextVerticalAlignment', 'middle', ...
'DefaultTextHorizontalAlignment', 'left'
